[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "embedding_tools"
version = "0.1.0"
description = "Utilities for embedding experiments with cross-platform array support"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Nitin Borwankar", email = "nborwankar@gmail.com"},
]
keywords = ["embeddings", "machine-learning", "numpy", "mlx", "apple-silicon"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = [
    "numpy>=1.21.0",
]

[project.optional-dependencies]
mlx = ["mlx>=0.0.7"]
torch = ["torch>=2.0.0"]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "isort>=5.10.0",
    "flake8>=4.0.0",
]
all = ["mlx>=0.0.7", "torch>=2.0.0"]

[project.urls]
Homepage = "https://github.com/nborwankar/embedding_tools"
Repository = "https://github.com/nborwankar/embedding_tools"
Issues = "https://github.com/nborwankar/embedding_tools/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["embedding_tools*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']

[tool.isort]
profile = "black"
line_length = 100
